### ISSUE TITLE
Tutorial 6 off-chain storage doesn't work

### ISSUE THREAD

**Issue by qwadratic** [MinaProtocol/docs2#695]
[Tutorial 6](https://docs.minaprotocol.com/zkapps/tutorials/offchain-storage): 
- The code for the tutorial comes with a different project structure which the tutorial does not refer to. Also in the `06-offchain-storage` folder, there is `ui/pages` directory which seems to be added by mistake
- The `contracts/src` directory has `SignedMessageBoard` which is not covered in the tutorial. Anyway, I am not able to run it (see the error message below) and unfortunately, I can’t find a way to fix it.
```
/Users/ii/mina/docs2/examples/zkapps/06-offchain-storage/offchain-storage-zkapp/contracts/node_modules/o1js/dist/node/bindings/compiled/_node_bindings/snarky_js_node.bc.cjs:7467
         throw err;
         ^

Error: "Assert_failure src/lib/transaction_logic/zkapp_command_logic.ml:1286:17"
    at Object.sendTransaction (o1js/dist/node/lib/mina.js:249:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async sendTransaction (o1js/dist/node/lib/mina.js:745:12)
    at async Object.send (o1js/dist/node/lib/mina.js:176:24)
    at async main (file:///Users/ii/mina/docs2/examples/zkapps/06-offchain-storage/offchain-storage-zkapp/contracts/build/src/messageBoardMain.js:29:5)
```
- For some reason, the tutorial asks the user to deploy the app to Berkeley, however, in other tutorials, we are happy to have local deployment.
- The correct command to run the off-chain storage server should be `node offchain-storage-zkapp/contracts/node_modules/experimental-offchain-zkapp-storage/build/src/server/storageServer.js`
- For some reason when I do “zk deploy” I get the following error
```
Failed to send transactions to the relayer. Errors: Couldn't send zkApp command: (Verification_failed
 "Invalid_signature: [B62qmVz7pPiLXPvz2nPkuK3K5akjrePAVtdBVMfeyixrccgqKTQte8K]") 
```
however other contracts are deploying successfully with the same feePayer account.
- As a result, I am unable to run the tutorial

**Comment by dkijania** [comment]
Fixed by #1254, merged today.

The complaint was that the tutorial's project structure did not match the code it pointed at. Both are now real and they match: `examples/zkapps/06-offchain-storage` exists — it never did before — and the page is built around it.

The page also no longer teaches the single-server storage library it was written against. That library was last published on 2022-11-17 and pinned o1js 0.12.1, which is a large part of why this tutorial could not be made to work. It now uses the offchain state API that o1js ships in-house, runs on a local blockchain with no server and no funded accounts, and is covered by 9 tests that CI runs on every pull request.

Thanks for the report — it stayed accurate for two years.
